In [5]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [8]:
new_arr=arr+3   # sabhi element me 3 add ho jayega
new_arr 

array([4, 5, 6, 7])

In [9]:
# add two Array
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
addedArr=arr1+arr2
addedArr

array([ 7,  9, 11, 13, 15])

In [12]:
# add Operation use
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
addedArr=np.add(arr1,arr2)
addedArr

array([ 7,  9, 11, 13, 15])

In [13]:
# add two 2D Array
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[6,7,8],[9,10,11]])
addedArr=arr1+arr2
addedArr

array([[ 7,  9, 11],
       [13, 15, 17]])

In [14]:
# add Operation use Two 2D array
# add two 2D Array
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[6,7,8],[9,10,11]])
addedArr=np.add(arr1,arr2)
addedArr

array([[ 7,  9, 11],
       [13, 15, 17]])