#create Numpy array using numpy function

In [1]:
import numpy as np

In [7]:
# Create Empty array

arr=np.empty((3,4))    #aise likhane par garbage values fill ho jata hai 
print(arr)

[[4.94e-322 4.94e-322 4.94e-322 4.94e-322]
 [4.94e-322 4.94e-322 4.94e-322 4.94e-322]
 [4.94e-322 4.94e-322 4.94e-322 4.94e-322]]


In [12]:
arr=np.empty((4,3),dtype=str) # pura empty print karana ho to (dtype=str) change karna hoga
                                #aur (arr.fill(" ") karna hoag

arr.fill(" ")
print(arr)

[[' ' ' ' ' ']
 [' ' ' ' ' ']
 [' ' ' ' ' ']
 [' ' ' ' ' ']]


##arange function

In [14]:
arr=np.arange(4)  #0 se start karke 4 tak (4 ko include nahi karta) numbers bana deta hai.
print(arr)

[0 1 2 3]


#Diagonal me 1 print karana

In [20]:
arr = np.eye(3)  # identity matrix banana diagonal me 1 hota hai baaki sab jagah 0
arr = arr.astype(int)
print(arr)
print(type(arr))
print("your arry is:-",arr.ndim,"D")

[[1 0 0]
 [0 1 0]
 [0 0 1]]
<class 'numpy.ndarray'>
your arry is:- 2 D


In [26]:
arr = np.linspace(1,10,num=5)   # 1 se 10 ke beech me 5 equal parts banayega
                                #(Gap = (10 - 1) / (5 - 1) = 9 / 4 = 2.25)
print(arr)
print("your arry is:-",arr.ndim,"D")

[ 1.    3.25  5.5   7.75 10.  ]
your arry is:- 1 D


In [30]:
arr = np.linspace(1,10,num=5)  
arr = arr.astype(int)  # yaha int me convert kar 
print(arr)
print("your arry is:-",arr.ndim,"D")

[ 1  3  5  7 10]
your arry is:- 1 D


In [31]:
arr = np.linspace(1,20,num=5)  
arr = arr.astype(int)  # yaha int me convert kar 
print(arr)
print("your arry is:-",arr.ndim,"D")

[ 1  5 10 15 20]
your arry is:- 1 D
