#create Numpy array with Random numbers

In [1]:
import numpy as np

#use random.rand(n)

In [3]:
var=np.random.rand(4) # Ye 4 random numbers generate Sab numbers 0 se 1 ke beech (0 ≤ x < 1) hote hain
print(var)

[0.52541993 0.83758931 0.34926281 0.55041258]


In [4]:
# Ye 2 rows aur 5 columns ka array (matrix) banata hai
# Har element random float number hota hai (0 se 1 ke beech)

var=np.random.rand(2,5) 
print(var)

[[0.22636414 0.15154465 0.43657164 0.83940411 0.58889502]
 [0.54975087 0.96177066 0.14948895 0.21154445 0.13503127]]


#use randn()

In [7]:
# Ye 5 random numbers generate karta hai
#Lekin ye numbers normal distribution (Gaussian distribution) follow karte hainvar = np.random.randn(5)

# rand() → 0 se 1 ke beech numbers
# randn() → mean = 0 aur negative + positive dono values

var = np.random.randn(5)
print(var)

[ 2.04389322 -1.06127063 -0.14927113  0.48824142  2.83138794]


In [9]:
# np.random.ranf(4)
# 4 random numbers generate karta hai
# range: 0 se 1 ke beech (0 ≤ x < 1)
# output floats me hota hai

# rand() → 0–1 random numbers
# ranf() → 0–1 random numbers (same kaam 😄)
# randn() → negative + positive random numbers (center 0)

var = np.random.ranf(4)
print(var)

[0.09728384 0.52390149 0.78667299 0.4047785 ]


In [10]:
#Ye 5 random integers generate karta hai
#Range hoti hai: 5 se 20 ke beech (20 include nahi hota)

# 5 → start (include hota hai)
#20 → end (exclude hota hai)
#5 → total numbers chahiye

var=np.random.randint(5,20,5)
print(var)

[18 13  8 10  8]
