In [1]:
import numpy as np

In [2]:
#Normally NumPy default me int64 use karta hai
x=np.array([1,2,3,4], dtype=np.int8)  # isase kisi bade datatype ko chhote me change kar rahe hai

In [3]:
x

array([1, 2, 3, 4], dtype=int8)

In [4]:
print(x)

[1 2 3 4]


In [5]:
x=np.array([1,2,3,4], dtype="f") # ye float me change kar deta hai
x

array([1., 2., 3., 4.], dtype=float32)

#function change

In [9]:
x2=np.array([1,2,3,4,5])
new=np.float32(x2)
print(x2)
print("Data type:",x2.dtype)
print(new)
print("New Data type:",new.dtype)

[1 2 3 4 5]
Data type: int64
[1. 2. 3. 4. 5.]
New Data type: float32


In [12]:
x2=np.array([1,2,3,4,5])
new=np.float32(x2)
new_one=np.int_(new)
print(x2)
print("Data type:",x2.dtype)
print(new)
print("New Data type:",new.dtype)
print(new_one)
print("New_one Data type:",new_one.dtype)

[1 2 3 4 5]
Data type: int64
[1. 2. 3. 4. 5.]
New Data type: float32
[1 2 3 4 5]
New_one Data type: int64


In [15]:
x3=np.array([1,2,3,4])
new_x3=x3.astype(float) # int se float me change karne ke liye use karte hai
print(x3)
print(new_x3)

[1 2 3 4]
[1. 2. 3. 4.]
