# shape @ Reshaing in Numpy array

In [22]:
import numpy as np 

In [12]:
x =np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print(" ")
print(x.shape) # ye array kai shape batata hai

[[1 2 3 4]
 [5 6 7 8]]
 
(2, 4)


In [13]:
var=np.array([1,2,3],ndmin=4) #ndmin=4 matlab array ko 4D bana dega
print(var)
print("array shape:-",var.shape)

[[[[1 2 3]]]]
array shape:- (1, 1, 1, 3)


In [25]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print("change array \n", arr.reshape(3,3)) # structure change karta hai

[1 2 3 4 5 6 7 8 9]
change array 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
print("array shape",arr.shape)
new_arr=arr.reshape(2,3,2)
print("change array \n",new_arr)
print("array shape",new_arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
array shape (12,)
change array 
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
array shape (2, 3, 2)
