In [1]:
import numpy as np

a = np.array([1,2,3])
b = 2

print(a + b)

[3 4 5]


In [4]:
arr1 = np.array([1,2,3,4])
print(arr1)
print("Array shape:-",arr1.shape)

[1 2 3 4]
Array shape:- (4,)


In [5]:
arr2 = np.array([[1],[2],[3]])
print(arr2)
print("Array shape:-",arr2.shape)

[[1]
 [2]
 [3]]
Array shape:- (3, 1)


In [7]:
print(arr1+arr2)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
