#create Numpy array using numpy function

In [2]:
import numpy as np

In [8]:
#zero 0's array

arr=np.zeros(4)
print(arr)
print(type(arr))
print(arr.dtype)
print("your array Dimension:-",arr.ndim)

[0. 0. 0. 0.]
<class 'numpy.ndarray'>
float64
your array Dimension:- 1


In [10]:
arr=np.zeros((4,3))
print(arr)
print(type(arr))
print(arr.dtype)
print("your array Dimension:-",arr.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
float64
your array Dimension:- 2


In [14]:
#(4,3,2) matlab:
#4 blocks
#har block me 3 rows
#har row me 2 elements

arr=np.zeros(((4,3,2)))
print(arr)
print(type(arr))
print(arr.dtype)
print("your array Dimension:-",arr.ndim)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
<class 'numpy.ndarray'>
float64
your array Dimension:- 3
