#create Numpy array using numpy function

In [7]:
import numpy as np

In [11]:
# create one's array  
arr=np.ones(4)
print(arr)
print(type(arr))
print(arr.dtype)
print("your array Dimension:-",arr.ndim)

[1. 1. 1. 1.]
<class 'numpy.ndarray'>
float64
your array Dimension:- 1


In [12]:
arr=np.ones((4,2))
print(arr)
print(type(arr))
print(arr.dtype)
print("your array Dimension:-",arr.ndim)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>
float64
your array Dimension:- 2


In [17]:
arr=np.ones(((3,4,4)))
arr=arr.astype(int)  # ye float se int me convert kar dega 
print(arr)
print(type(arr))
print(arr.dtype)
print("your array Dimension:-",arr.ndim)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
<class 'numpy.ndarray'>
int64
your array Dimension:- 3


In [19]:
arr=np.ones((4,5))
arr=arr.astype(int)
print(arr)
print(arr.dtype)
print("your array Dimension:-",arr.ndim)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
int64
your array Dimension:- 2


In [20]:
arr = np.full((3,4),100)   # 3 row aur 4 column aur har element 100 hoga
print(arr)
print(type(arr))
print(arr.dtype)
print("your array Dimension:-",arr.ndim)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
<class 'numpy.ndarray'>
int64
your array Dimension:- 2
