In [1]:
# indexing , slicing in numpy Array
# Indexing aur Slicing NumPy me data access karne ka tareeka hai

In [2]:
import numpy as np

arr = np.array([10,20,30,40])
print(arr[2])

30


In [4]:
#2D Array Indexing
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr[1][2])  # row 1, column 2

6


In [12]:
print(arr[1,2]) 

6


In [13]:
arr = np.array([10,20,30,40,50])

print(arr[1:4])   # Rule: [start : end]  → end include nahi hota

[20 30 40]


In [14]:
# Step slicing
print(arr[0:5:2])

[10 30 50]


In [15]:
# 2D Slicing
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr[:,1:])

[[2 3]
 [5 6]]


In [16]:
# Negative Indexing
print(arr[-1])  # Last element

[4 5 6]


In [17]:
# Full Slice
arr[:]

array([[1, 2, 3],
       [4, 5, 6]])