In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print("Min :-",np.min(arr)) 
print("max :-",np.max(arr))

Min :- 1
max :- 5


In [5]:
arr = np.array([1,2,3,4,5])
print("Min :-",np.argmin(arr))   #ye index ka min deta hai 
print("max :-",np.argmax(arr))   #ye index ka max deta hai 

Min :- 0
max :- 4


In [11]:
var=np.array([[1,2,3,4],[5,6,7,8]])
print(var)
print("har column ka minimum value:- \n",np.min(var,axis=0))

[[1 2 3 4]
 [5 6 7 8]]
har column ka minimum value:- 
 [1 2 3 4]


In [13]:
var=np.array([[1,2,3,4],[5,6,7,8]])
print(var)
print("har row ka minimum value:- \n",np.min(var,axis=1))

[[1 2 3 4]
 [5 6 7 8]]
har row ka minimum value:- 
 [1 5]


In [14]:
var=np.array([[1,2,3,4],[5,6,7,8]])
print(var)
print("har column ka max value:- \n",np.max(var,axis=0))

[[1 2 3 4]
 [5 6 7 8]]
har column ka max value:- 
 [5 6 7 8]


In [16]:
var=np.array([[1,2,3,4],[5,6,7,8]])
print(var)
print("har row ka max value:- \n",np.max(var,axis=1))

[[1 2 3 4]
 [5 6 7 8]]
har row ka max value:- 
 [4 8]


In [20]:
import numpy as np

a = np.array([10,20,30])
b = np.array([2,5,10])

print(np.add(a,b))


[12 25 40]


In [21]:
print(np.subtract(a,b))


[ 8 15 20]


In [22]:
print(np.multiply(a,b))


[ 20 100 300]


In [23]:
print(np.divide(a,b))


[5. 4. 3.]


In [24]:
print(np.mod(a,b))

[0 0 0]


In [25]:
print(np.power(a,2))

[100 400 900]
